.globl hw_bswap16
.globl hw_bswap32
.globl hw_bswap64
.globl _cu_memcpy
.globl _cu_memmove
.globl _cu_memcmp
.globl _cu_memset
.globl cu_memzero
.globl cu_memtest
.globl cu_va_start
.globl cu_va_arg

.text

hw_bswap16:
    ret

hw_bswap32:
    ret

hw_bswap64:
    ret

_cu_memcpy:
    ret

_cu_memmove:
    ret

_cu_memcmp:
    ret

_cu_memset:
    ret

cu_memzero:
    ret

cu_memtest:
    ret

cu_va_start:
    ret

cu_va_arg:
    ret
