.globl hw_bswap16
.globl hw_bswap32
.globl hw_bswap64
.globl _cu_memcpy
.globl _cu_memmove
.globl _cu_memcmp
.globl _cu_memset
.globl cu_memzero
.globl cu_memtest
.globl cu_va_start
.globl cu_va_arg

.text
.align 16

hw_bswap16:
    rts

hw_bswap32:
    rts

hw_bswap64:
    rts

_cu_memcpy:
    rts

_cu_memmove:
    rts

_cu_memcmp:
    rts

_cu_memset:
    rts

cu_memzero:
    rts

cu_memtest:
    rts

cu_va_start:
    rts

cu_va_arg:
    rts
